#!/bin/bash

#usage: mean_guide galaxy_number output_directory
TMP=`mktemp -d`
HASH="${1#"${1%???}"}"
if [ ! -d "/extra/wayne1/preserve/antholn1/SDSS_DR12_Aligned/$HASH/$1" ]
then
    echo "ERROR: GALAXY NUMBER DOES NOT EXIST"
    exit 1
fi

if [ ! -d "$2" ]
then
    echo "ERROR: OUTPUT DIRECTORY DOES NOT EXIST"
    exit 1
fi

cp -r /extra/wayne1/preserve/antholn1/SDSS_DR12_Aligned/$HASH/"$1" $TMP/"$1"
unxz $TMP/"$1"/*
mkdir $TMP/meanFITS/
/extra/wayne1/preserve/skylarjh/skylars_guided_runs/mean/createMeans $TMP/meanFITS/"$1".fits $TMP/"$1"/"$1"_r.fits $TMP/"$1"/"$1"_g.fits $TMP/"$1"/"$1"_i.fits $TMP/"$1"/"$1"_u.fits $TMP/"$1"/"$1"_z.fits
mkdir $TMP/SDSS/
mkdir $TMP/SDSS/G.in
mkdir $TMP/SDSS/G.out
mkdir $TMP/SDSS/G.tmp
mkdir $TMP/guide
cp -r $TMP/meanFITS/"$1".fits $TMP/SDSS/G.in/
/extra/wayne1/preserve/skylarjh/SpArcFiRe/scripts/SpArcFiRe -convert-FITS $TMP/SDSS/G.in $TMP/SDSS/G.tmp $TMP/SDSS/G.out -writeBulgeMask 1
cp -r $TMP/SDSS/G.out $TMP/guide/
for waveband in $(ls $TMP/"$1" | sed -e 's/\.fits$//')
do
    for threshold in 0 0.25 0.5 0.75 1
    do
        rm -rf $TMP/SDSS/G.in/*
        cp $TMP/"$1"/"$waveband".fits $TMP/SDSS/G.in/"$1".fits
        /extra/wayne1/preserve/skylarjh/SpArcFiRe/scripts/SpArcFiRe -convert-FITS -guide_dir $TMP/guide $TMP/SDSS/G.in $TMP/SDSS/G.tmp $TMP/SDSS/G.out -writeBulgeMask 1 -imageGuidingThreshold "$threshold"
        mkdir -p "$2"/$HASH/"$1"/"$threshold"/
        cp $TMP/SDSS/G.out/"$1"/"$1"-H_clusMask-merged.png "$2"/$HASH/"$1"/"$threshold"/"$waveband".png
    done
done
rm -rf $TMP

