#!/bin/sh
# Actually, I lied.  The solution to the exam question is in "rename.209".
# This one is more complicated than what was necessary for the exam.

# check for options
ASK='-i' # default to always ask before overwriting.
ECHO_ONLY=false
case "$1" in
-f) ASK=''; shift;;
-n) ECHO_ONLY=true; shift;;
esac

# check for erroneous use of / in sed separator.
case "$1" in
*/*) echo "Use ; instead of / as separator"
    exit 1
    ;;
esac

pattern="$1"
shift
for i
do
    case "$pattern" in
	# first case handles "s/foo/bar/g"
	*\;*\;*) newname=`echo "$i" | sed "s;$pattern"`;;

	# second case handles a "once per file" substitution; you don't
	# supply the outside slashes, this pattern does it for you.
	*) newname=`echo "$i" | sed "s;$pattern;"`;;
    esac
    case "$newname" in
	"$i") ;;    # same name, don't do anything, else mv(1) will complain.
	*) if "$ECHO_ONLY"; then
	    echo mv $ASK "$i" "$newname"
	   else
	    mv $ASK "$i" "$newname"
	   fi
	;;
    esac
done
