#!/bin/sh
# USAGE: lines N1 N2 [file]
l1="$1"
l2="$2"
shift 2
if [ $l1 -lt 1 ]; then l1=1; fi
if [ $l2 -lt 1 ]; then l2=1; fi
case $# in
0) sed -n "$l1,${l2}p;${l2}q" ;;
*)
    for i
    do
	sed -n "$l1,${l2}p;${l2}q" "$i"
    done
    ;;
esac
